"""initial

Revision ID: 5db63297d8dc
Revises: 
Create Date: 2023-10-09 18:33:29.974280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5db63297d8dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('birthdate', sa.Date(), nullable=True))
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.drop_column('contacts', 'birthday')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_column('contacts', 'birthdate')
    # ### end Alembic commands ###
